### ISSUE TITLE
Can this extract text from image-only PDFs?

### ISSUE THREAD

**Issue by vincent-czi** [huridocs/pdf-text-extraction#1]
I have a PDF that is composed only of photos of text: can pdf-text-extraction pull text from that?

Specifically, it's a 5-page PDF that is purely photos of pages of a book. It's intentionally supposed to be representative of a worst-case scan of a document. It's just 5 smartphone photos of 5 pages, stitched together sequentially into a PDF (done by opening the images together in Mac's Preview then printing as PDF). When I run it through the pdf-text-extraction service, I'm not getting any text. Is it able to perform OCR on the document as part of pulling out the text, or is it more about performing segmentation and then leveraging those segmentations to pull out embedded text strings in an intelligent way?

I'm running this on an older Mac laptop (2019), so using it in the no GPU mode. Here's what I'm running.

```
make start_no_gpu
curl -X POST -F 'file=@/path/to/my_bad_scan.pdf' localhost:5080/text
```

But then the output I get is simply the below. It takes a little under 2 minutes to run in total.
```
"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
```

So it appears that it's not managing to extract any text info from the images, even though they are images of a book and readable to human eyes / OCR. Is there a setting I'm missing, or is this intentional and the pdf-text-extraction tool isn't actually meant to do OCR? Thanks very much!

**Comment by ali6parmak** [comment]
Hi, unfortunately our service does not support OCR at least for now. But maybe in the future this could change. Thanks for your interest!

**Comment by txau** [comment]
@vincent-czi OCRing the PDF needs to be done apart before segmenting it. We use two different approaches for segmentation, one uses a computer vision approach (slower, requires more resources but higher accuracy), the other one uses the text layer of the documents (faster and cheaper but lower accuracy).

You may be interested in checking our repo for the wrapper for tesseract OCR: https://github.com/huridocs/pdf_ocr_service

**Comment by vincent-czi** [comment]
Thank you! And thanks for the link to the OCR service, I wasn't aware of it previously!
