### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gbanusi** [huridocs/pdf-text-extraction#2]
Is this ok:

![image](https://github.com/user-attachments/assets/700579b5-4526-48a7-a2b0-83b7afdbaa47)

I get the response...
I'm using macbook M3.

Is it possible to extract markdown here?

**Comment by gabriel-piles** [comment]
The logs are misleading, but they are correct. They are from another library that we don't yet know how to avoid generating this kind of message.

The service result is a JSON, which could be easily converted to Markdown with a small piece of code or with an online converter.

We will keep your suggestion for implementing a Markdown output in mind for the future.

Thank you.
